easy_admin:
    entities:
        # List the entity class name you want to manage
        Cart:
            class: App\Entity\Cart
        CartProduct:
            class: App\Entity\CartProduct
        Collection:
            class: App\Entity\Collection
        Product:
            class: App\Entity\Product
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }

        User:
            class: App\Entity\User

    site_name: 'iim-2019-symfony-ecommerce-admin'
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@VichUploader/Form/fields.html.twig'